extends Reference

func run(t):
	var script = load("res://app/presentation/story_motion.gd")
	t.check(script != null, "event-driven presentation model exists")
	if script == null:
		return false
	var Game = load("res://core/campaign/game_state.gd")
	var game = Game.new()
	game.start(12345)
	var motion = script.new()
	motion.sync(game)
	var before = game.to_data()
	motion.advance(10.0)
	t.check(t.equal(before, game.to_data()), "ambient animation never mutates state or RNG")
	var result = game.execute({"type": "move", "target": "first_1"})
	motion.observe(result.events, game)
	t.check(motion.hero_from != motion.hero_to, "move event starts visual travel")
	before = game.to_data()
	motion.advance(0.15)
	t.check(motion.hero_position() != motion.hero_to, "visual position can lag resolved state")
	motion.advance(1.0)
	t.check(motion.hero_position() == motion.hero_to and t.equal(before, game.to_data()), "travel completes without state mutation")
	result = game.execute({"type": "reveal"})
	motion.observe(result.events, game)
	t.check(motion.reveal < 1.0, "reveal animates")
	motion.advance(2.0)
	t.check(motion.reveal == 1.0, "revealed map becomes visible")
	game.execute({"type": "move", "target": "second_0"})
	game.execute({"type": "engage"})
	result = game.execute({"type": "attack"})
	motion.observe(result.events, game)
	t.check(motion.impact > 0.0 and motion.damage > 0, "combat events drive impact and damage")
	before = game.to_data()
	motion.set_reduced(true)
	motion.advance(0.01)
	t.check(motion.impact == 0.0 and motion.hero_position() == motion.hero_to, "reduced motion settles effects")
	t.check(t.equal(before, game.to_data()), "reduced motion preserves canonical state")
	motion.sync(game)
	t.check(motion.impact == 0.0, "loading does not replay old combat")
	return true
